export const studentEnroll = {
  firstName: '',
  middleName: '',
  lastName: '',
  fatherName: '',
  dob: '',
  gender: 'male',
  mobile: '',
  email: '',
  addressLine1: '',
  addressLine2: '',
  city: '',
  state: '',
  pincode: '',
  remarks: '',
  pending: false,
};
